with unioned as (
select
--player_id,
nickname as player,
real_name,
age,
country,
current_team,
teams,
total_kills,
total_deaths,
headshot_percentage,
damage_per_round,
grenade_dmg_per_round,
maps_played,
rounds_played,
total_kills - total_deaths as kd_difference,
total_kills / total_deaths as kd_ratio,
kills_per_death,
kills_per_round,
assists_per_round,
deaths_per_round,
saved_by_teammate_per_round,
saved_teammates_per_round,
rounds_with_kills,
total_opening_kills,
total_opening_deaths,
opening_kill_ratio,
opening_kill_rating,
team_win_percent_after_first_kill,
first_kill_in_won_rounds,
zero_kill_rounds,
one_kill_rounds,
two_kill_rounds,
three_kill_rounds,
four_kill_rounds,
five_kill_rounds,
rifle_kills,
sniper_kills,
smg_kills,
pistol_kills,
grenade_kills,
other_kills,
rating,
null as kast,
null as impact
from etl.playerstat_source3_transform 
UNION
(
SELECT
player,
null as real_name,
null as age,
country,
null as current_team,
teams,
total_kills,
total_deaths,
headshot_percentage,
null as damage_per_round,
grenade_damage_per_round as grenade_dmg_per_round,
maps_played,
rounds_played,
null as kills_per_death,
kd_difference,
kd_ratio,
kills_per_round,
assists_per_round,
deaths_per_round,
saved_by_teammate_per_round,
teammate_saved_per_round as saved_teammates_per_round,
null as rounds_with_kills,
null as total_opening_kills,
null as total_opening_deaths,
null as opening_kill_ratio,
null as opening_kill_rating,
null as team_win_percent_after_first_kill,
null as first_kill_in_won_rounds,
null as zero_kill_rounds,
null as one_kill_rounds,
null as two_kill_rounds,
null as three_kill_rounds,
null as four_kill_rounds,
null as five_kill_rounds,
null as rifle_kills,
null as sniper_kills,
null as smg_kills,
null as pistol_kills,
null as grenade_kills,
null as other_kills,
rating,
kast,
impact
from etl.playerstat_source2_transform
)
order by player, maps_played
),
ranked as (
	select *,
	dense_rank() over (partition by player order by maps_played desc) as newer_data
	from unioned
)